version: '3.8'

services:
  app:
    build: .                 # Build the image using the Dockerfile in the current directory
    container_name: astro-env
    volumes:
      - .:/app               # Mount current directory to /app inside container
      - /app/node_modules     # Isolate node_modules directory
    ports:
      - "4321:4321"           
    working_dir: /app         # Set the working directory to /app
    command: npm run dev      # Command to run inside the container
    stdin_open: true          # Keep stdin open for interactive use
    tty: true                 # Allocate a pseudo-TTY
    environment:
      - NODE_ENV=development

